
// This file has been generated by the GUI designer. Do not modify.
namespace GoGo
{
	public partial class AddWindows2
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Entry entry2;
		
		private global::Gtk.Entry entry1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Entry entry3;
		
		private global::Gtk.Entry entry4;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Entry entry5;
		
		private global::Gtk.Entry entry6;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Entry entry7;
		
		private global::Gtk.Button btnNuevo;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Entry entry8;
		
		private global::Gtk.Entry entry9;
		
		private global::Gtk.Entry entry10;
		
		private global::Gtk.Entry entry11;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Button btnActualizar;
		
		private global::Gtk.Button btnBorrar;
		
		private global::Gtk.Button btnGuardar;
		
		private global::Gtk.Button btnLimpiar;
		
		private global::Gtk.Button btnCancel;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeview1;
		
		private global::Gtk.Button btnBuscar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GoGo.AddWindows2
			this.Name = "GoGo.AddWindows2";
			this.Title = global::Mono.Unix.Catalog.GetString ("Formato No. 2");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child GoGo.AddWindows2.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w1.X = 11;
			w1.Y = 8;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry2 = new global::Gtk.Entry ();
			this.entry2.WidthRequest = 79;
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '•';
			this.fixed1.Add (this.entry2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry2]));
			w2.X = 9;
			w2.Y = 25;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.WidthRequest = 113;
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.fixed1.Add (this.entry1);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry1]));
			w3.X = 92;
			w3.Y = 26;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Ruta");
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w4.X = 94;
			w4.Y = 7;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Cant.");
			this.fixed1.Add (this.label3);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
			w5.X = 214;
			w5.Y = 5;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry3 = new global::Gtk.Entry ();
			this.entry3.WidthRequest = 40;
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '•';
			this.fixed1.Add (this.entry3);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry3]));
			w6.X = 210;
			w6.Y = 26;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry4 = new global::Gtk.Entry ();
			this.entry4.WidthRequest = 32;
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '•';
			this.fixed1.Add (this.entry4);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry4]));
			w7.X = 258;
			w7.Y = 26;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Kgs");
			this.fixed1.Add (this.label4);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
			w8.X = 261;
			w8.Y = 5;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry5 = new global::Gtk.Entry ();
			this.entry5.WidthRequest = 73;
			this.entry5.CanFocus = true;
			this.entry5.Name = "entry5";
			this.entry5.IsEditable = true;
			this.entry5.InvisibleChar = '•';
			this.fixed1.Add (this.entry5);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry5]));
			w9.X = 297;
			w9.Y = 26;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry6 = new global::Gtk.Entry ();
			this.entry6.WidthRequest = 71;
			this.entry6.CanFocus = true;
			this.entry6.Name = "entry6";
			this.entry6.IsEditable = true;
			this.entry6.InvisibleChar = '•';
			this.fixed1.Add (this.entry6);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry6]));
			w10.X = 375;
			w10.Y = 26;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Gasto");
			this.fixed1.Add (this.label6);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
			w11.X = 390;
			w11.Y = 5;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry7 = new global::Gtk.Entry ();
			this.entry7.WidthRequest = 40;
			this.entry7.CanFocus = true;
			this.entry7.Name = "entry7";
			this.entry7.IsEditable = true;
			this.entry7.InvisibleChar = '•';
			this.fixed1.Add (this.entry7);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry7]));
			w12.X = 453;
			w12.Y = 26;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnNuevo = new global::Gtk.Button ();
			this.btnNuevo.CanFocus = true;
			this.btnNuevo.Name = "btnNuevo";
			this.btnNuevo.UseStock = true;
			this.btnNuevo.UseUnderline = true;
			this.btnNuevo.Label = "gtk-new";
			this.fixed1.Add (this.btnNuevo);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnNuevo]));
			w13.X = 12;
			w13.Y = 60;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("U");
			this.fixed1.Add (this.label7);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label7]));
			w14.X = 467;
			w14.Y = 4;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry8 = new global::Gtk.Entry ();
			this.entry8.WidthRequest = 40;
			this.entry8.CanFocus = true;
			this.entry8.Name = "entry8";
			this.entry8.IsEditable = true;
			this.entry8.InvisibleChar = '•';
			this.fixed1.Add (this.entry8);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry8]));
			w15.X = 502;
			w15.Y = 26;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry9 = new global::Gtk.Entry ();
			this.entry9.WidthRequest = 40;
			this.entry9.CanFocus = true;
			this.entry9.Name = "entry9";
			this.entry9.IsEditable = true;
			this.entry9.InvisibleChar = '•';
			this.fixed1.Add (this.entry9);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry9]));
			w16.X = 549;
			w16.Y = 26;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry10 = new global::Gtk.Entry ();
			this.entry10.WidthRequest = 40;
			this.entry10.CanFocus = true;
			this.entry10.Name = "entry10";
			this.entry10.IsEditable = true;
			this.entry10.InvisibleChar = '•';
			this.fixed1.Add (this.entry10);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry10]));
			w17.X = 596;
			w17.Y = 26;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry11 = new global::Gtk.Entry ();
			this.entry11.WidthRequest = 40;
			this.entry11.CanFocus = true;
			this.entry11.Name = "entry11";
			this.entry11.IsEditable = true;
			this.entry11.InvisibleChar = '•';
			this.fixed1.Add (this.entry11);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry11]));
			w18.X = 643;
			w18.Y = 26;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("+ ");
			this.fixed1.Add (this.label10);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label10]));
			w19.X = 607;
			w19.Y = 6;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("+ / -");
			this.fixed1.Add (this.label9);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label9]));
			w20.X = 554;
			w20.Y = 4;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Dia");
			this.fixed1.Add (this.label11);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label11]));
			w21.X = 650;
			w21.Y = 7;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnActualizar = new global::Gtk.Button ();
			this.btnActualizar.CanFocus = true;
			this.btnActualizar.Name = "btnActualizar";
			this.btnActualizar.UseStock = true;
			this.btnActualizar.UseUnderline = true;
			this.btnActualizar.Label = "gtk-refresh";
			this.fixed1.Add (this.btnActualizar);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnActualizar]));
			w22.X = 75;
			w22.Y = 60;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnBorrar = new global::Gtk.Button ();
			this.btnBorrar.CanFocus = true;
			this.btnBorrar.Name = "btnBorrar";
			this.btnBorrar.UseStock = true;
			this.btnBorrar.UseUnderline = true;
			this.btnBorrar.Label = "gtk-delete";
			this.fixed1.Add (this.btnBorrar);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnBorrar]));
			w23.X = 166;
			w23.Y = 61;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnGuardar = new global::Gtk.Button ();
			this.btnGuardar.CanFocus = true;
			this.btnGuardar.Name = "btnGuardar";
			this.btnGuardar.UseStock = true;
			this.btnGuardar.UseUnderline = true;
			this.btnGuardar.Label = "gtk-save";
			this.fixed1.Add (this.btnGuardar);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnGuardar]));
			w24.X = 241;
			w24.Y = 63;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnLimpiar = new global::Gtk.Button ();
			this.btnLimpiar.CanFocus = true;
			this.btnLimpiar.Name = "btnLimpiar";
			this.btnLimpiar.UseStock = true;
			this.btnLimpiar.UseUnderline = true;
			this.btnLimpiar.Label = "gtk-clear";
			this.fixed1.Add (this.btnLimpiar);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnLimpiar]));
			w25.X = 317;
			w25.Y = 63;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnCancel = new global::Gtk.Button ();
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseStock = true;
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = "gtk-cancel";
			this.fixed1.Add (this.btnCancel);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnCancel]));
			w26.X = 613;
			w26.Y = 63;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Alm.");
			this.fixed1.Add (this.label8);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label8]));
			w27.X = 506;
			w27.Y = 5;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Costo");
			this.fixed1.Add (this.label5);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
			w28.X = 309;
			w28.Y = 5;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView ();
			this.treeview1.WidthRequest = 661;
			this.treeview1.HeightRequest = 383;
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow.Add (this.treeview1);
			this.fixed1.Add (this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
			w30.X = 12;
			w30.Y = 97;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnBuscar = new global::Gtk.Button ();
			this.btnBuscar.CanFocus = true;
			this.btnBuscar.Name = "btnBuscar";
			this.btnBuscar.UseUnderline = true;
			this.btnBuscar.Label = global::Mono.Unix.Catalog.GetString ("IMprimir");
			global::Gtk.Image w31 = new global::Gtk.Image ();
			w31.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-print", global::Gtk.IconSize.Menu);
			this.btnBuscar.Image = w31;
			this.fixed1.Add (this.btnBuscar);
			global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnBuscar]));
			w32.X = 398;
			w32.Y = 59;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 698;
			this.DefaultHeight = 533;
			this.Show ();
			this.btnNuevo.Clicked += new global::System.EventHandler (this.OnBtnNuevoClicked);
			this.btnActualizar.Clicked += new global::System.EventHandler (this.OnBtnActualizarClicked);
			this.btnBorrar.Clicked += new global::System.EventHandler (this.OnBtnBorrarClicked);
			this.btnGuardar.Clicked += new global::System.EventHandler (this.OnBtnGuardarClicked);
			this.btnLimpiar.Clicked += new global::System.EventHandler (this.OnBtnLimpiarClicked);
			this.btnCancel.Clicked += new global::System.EventHandler (this.OnBtnCancelClicked);
			this.btnBuscar.Clicked += new global::System.EventHandler (this.OnBtnBuscarClicked);
		}
	}
}
