
// This file has been generated by the GUI designer. Do not modify.
namespace GoGo
{
	public partial class WindowSearch
	{
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.RadioButton radiobutton3;
		
		private global::Gtk.Button btnAccept;
		
		private global::Gtk.Button btnCancel;
		
		private global::Gtk.RadioButton radiobutton6;
		
		private global::Gtk.RadioButton radiobutton5;
		
		private global::Gtk.Entry entry1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.RadioButton radiobutton4;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GoGo.WindowSearch
			this.Name = "GoGo.WindowSearch";
			this.Title = global::Mono.Unix.Catalog.GetString ("Buscar ");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child GoGo.WindowSearch.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Criterio de Busqueda");
			this.fixed2.Add (this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label1]));
			w1.X = 17;
			w1.Y = 7;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.radiobutton3 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Por Fecha"));
			this.radiobutton3.CanFocus = true;
			this.radiobutton3.Name = "radiobutton3";
			this.radiobutton3.DrawIndicator = true;
			this.radiobutton3.UseUnderline = true;
			this.radiobutton3.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.fixed2.Add (this.radiobutton3);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.radiobutton3]));
			w2.X = 18;
			w2.Y = 33;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnAccept = new global::Gtk.Button ();
			this.btnAccept.WidthRequest = 100;
			this.btnAccept.CanFocus = true;
			this.btnAccept.Name = "btnAccept";
			this.btnAccept.UseUnderline = true;
			this.btnAccept.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.btnAccept.Image = w3;
			this.fixed2.Add (this.btnAccept);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.btnAccept]));
			w4.X = 445;
			w4.Y = 188;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnCancel = new global::Gtk.Button ();
			this.btnCancel.WidthRequest = 100;
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.btnCancel.Image = w5;
			this.fixed2.Add (this.btnCancel);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.btnCancel]));
			w6.X = 322;
			w6.Y = 188;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.radiobutton6 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Rango de Fechas"));
			this.radiobutton6.CanFocus = true;
			this.radiobutton6.Name = "radiobutton6";
			this.radiobutton6.DrawIndicator = true;
			this.radiobutton6.UseUnderline = true;
			this.radiobutton6.Group = this.radiobutton3.Group;
			this.fixed2.Add (this.radiobutton6);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.radiobutton6]));
			w7.X = 52;
			w7.Y = 89;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.radiobutton5 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Fecha Especifica"));
			this.radiobutton5.CanFocus = true;
			this.radiobutton5.Name = "radiobutton5";
			this.radiobutton5.DrawIndicator = true;
			this.radiobutton5.UseUnderline = true;
			this.radiobutton5.Group = this.radiobutton3.Group;
			this.fixed2.Add (this.radiobutton5);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.radiobutton5]));
			w8.X = 54;
			w8.Y = 56;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.WidthRequest = 462;
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.fixed2.Add (this.entry1);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.entry1]));
			w9.X = 82;
			w9.Y = 155;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Lugar: ");
			this.fixed2.Add (this.label2);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label2]));
			w10.X = 36;
			w10.Y = 156;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.radiobutton4 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Por Lugar"));
			this.radiobutton4.CanFocus = true;
			this.radiobutton4.Name = "radiobutton4";
			this.radiobutton4.DrawIndicator = true;
			this.radiobutton4.UseUnderline = true;
			this.radiobutton4.Group = this.radiobutton3.Group;
			this.fixed2.Add (this.radiobutton4);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.radiobutton4]));
			w11.X = 16;
			w11.Y = 129;
			this.Add (this.fixed2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 549;
			this.DefaultHeight = 249;
			this.Show ();
			this.btnCancel.Clicked += new global::System.EventHandler (this.OnBtnCancelClicked);
		}
	}
}
